### ISSUE TITLE
Adaptação overleaf

### ISSUE THREAD

**Issue by anaptoro** [rafacho/templateLatexFEAGRI#1]
O overleaf não compila o template da forma que ele está.
Então caso queiram usar o overleaf no arquivo settings.tex é necessário remover a linha
`\documentclass[12pt,oneside,hidelinks,a4paper,final]{book}`
Em seguida copie essa mesma linha no arquivo tese_template.tex antes de input{settings}
Depois disso o documento compilará normalmente

**Comment by rafacho** [comment]
@anaptoro 
Atualização feita, obrigado
